### ISSUE TITLE
Pandas dependency

### ISSUE THREAD

**Issue by SeanDS** [numericalalgorithmsgroup/pybobyqa#15]
Great work on this! This seems to work pretty well for solving mode matching problems in optics, which is a very much non-convex (hence the name?) problem.

I have one gripe though: as far as I can tell, pandas is only used for diagnostics. Could this maybe be removed as an official dependency and instead be made available either as a setup extra or have Py-BOBYQA throw an error if pandas is not found when the diagnostics are run? I'm considering using the package with my own library but having pandas as a dependency when it's hardly used seems like overkill.

**Comment by lindonroberts** [comment]
Thanks - this is a good idea. Without pandas, the diagnostics could also be made available as a dictionary.

**Comment by lindonroberts** [comment]
I've made this change. For my own reference, I still need to test and update formal dependencies and documentation.

**Comment by SeanDS** [comment]
Great, thank you!
