### ISSUE TITLE
noisy and deterministic the same?

### ISSUE THREAD

**Issue by microprediction** [numericalalgorithmsgroup/pybobyqa#16]
Hi,  I just included py-bobyqa in a deriv-free benchmarking exercise I'm doing in the [HumpDay](https://github.com/microprediction/humpday/blob/main/humpday/optimizers/bobyqacube.py) package. I have quick newbie questions. If the objective is deterministic should I expect identical behaviour when objfun_has_noise=True/False ? 
If set to True, is there a noise parameter I should be tuning? 
-Peter

**Comment by lindonroberts** [comment]
Hi Peter - no, Py-BOBYQA will behave differently depending on how you set objfun_has_noise, even if the objective is deterministic. 

Aside from stochastic objective values giving the solver different information (and so it proceeds differently), some of the underlying algorithm parameters has different defaults depending on objfun_has_noise, based on what typically is a good value for deterministic/stochastic problems.

In some cases (particularly for reasonably simple, deterministic objectives) I expect that you would get a similar/identical final solution using both settings, but there are absolutely no guarantees for this, unfortunately.

**Comment by microprediction** [comment]
Thanks Lindon (I'm a fellow aussie btw). I see now that they were similar just by a fluke. Now I'm seeing the noisy version tend to outperform. ([example](https://github.com/microprediction/optimizer-elo-ratings/tree/main/results/leaderboards/overall))

**Comment by lindonroberts** [comment]
Interesting, thanks for letting me know!
