### ISSUE TITLE
np.int, and np.float- version 1.3?

### ISSUE THREAD

**Issue by cmbant** [numericalalgorithmsgroup/pybobyqa#17]
Would be nice to have pypi updated to avoid the numpy warnings!

I think you fixed some float, but there's also np.int at e.g. https://github.com/numericalalgorithmsgroup/pybobyqa/blob/master/pybobyqa/model.py#L68

**Comment by lindonroberts** [comment]
Thanks - good idea. I've created pypi version 1.3 (after fixing the np.int issue).
