### ISSUE TITLE
Non-convergence

### ISSUE THREAD

**Issue by cmbant** [numericalalgorithmsgroup/pybobyqa#18]
Below is some example code that appears not to converge, producing in log things like "INFO:root:Slow iteration (206 consecutive so far, max allowed 60)". It works without seek_global_minimum, and also when increasing rhobeg (the default value for which is probably too small in the example given the value of rhoend).

```

import numpy as np
import pybobyqa


mean = np.array([0.30245268, 0.61884443, 0.5])
cov = np.array(
    [[0.00796336, -0.0014805, -0.00479433], [-0.0014805, 0.00561415, 0.00434189],
     [-0.00479433, 0.00434189, 0.03208593]])
invcov = np.linalg.inv(cov)
scales = np.array([0.28867513, 0.28867513, 0.28867513])
baseline = np.array([0.55394102, 0.39624789, 0.04812677])

norm = np.log(np.sqrt(np.linalg.det(cov) * (2 * np.pi) ** 3))


def objfun(x):
    y = x * scales + baseline - mean
    return invcov.dot(y).dot(y) / 2 + norm

res=pybobyqa.solve(**{'objfun': objfun, 'x0': np.array(
    [0., 0., 0.]), 'bounds': np.array([[-1.91890799, -1.37264297, -0.16671603],
                                       [1.54519362, 2.09145865, 3.29738558]]), 'seek_global_minimum': True,
                  'maxfun': 30000, 'rhobeg': None, 'do_logging': True, 'rhoend': 0.05})

```

**Comment by lindonroberts** [comment]
Sorry for the very slow reply - I get bogged down with other work and don't have time to work through these issues!

When I run this with seek_global_minimum=False, I get termination "rho has reached rhoend", with minimum value f(xmin) = -4.0817. With seek_global_minimum=True, I get termination message "maximum number of unsuccessful restarts" with minimum value f(xmin) = -4.0825, which is a slight improvement.

I'm not sure if this is what you are seeing, but I would treat "maximum number of unsuccessful restarts" as a success message. Basically when seek_global_minimum=True, the solver tries to restart whenever rho reaches rhoend (the original termination scenario), to see if it can find a better region nearby that it perhaps hadn't seen. In this case, the termination message is saying that it tried this a few times and couldn't find anything better, so it didn't try to look any further. This behavior is controlled by the advanced options "restarts.max_unsuccessful_restarts" and "restarts.max_unsuccessful_restarts_total". 

Unfortunately I don't see those "Slow iteration (206 consecutive so far, max allowed 60)" message, but this does look like a bug of some kind with the slow iteration counter that I need to look into.

**Comment by cmbant** [comment]
I can still reproduce this, running with 

```
import logging
logging.basicConfig(level='DEBUG')
```
The start of the full log is attached (with Slow iteration getting larger than 60)
[log.txt](https://github.com/numericalalgorithmsgroup/pybobyqa/files/7211450/log.txt)

**Comment by lindonroberts** [comment]
Thanks - I found the issue: the counter of the number of slow iterations wasn't being reset when a restart is performed. This should be fixed in the latest commit.
