### ISSUE TITLE
Object function with self not working

### ISSUE THREAD

**Issue by tazuddin90** [numericalalgorithmsgroup/pybobyqa#25]
I am trying to use pybobyqa inside a class so I need to use obj(self,x) arguments. but it is showing error. Any way around ? Please help

**Comment by lindonroberts** [comment]
Hi, yes, the expectation is that the objective can be called as ```f = objective(x)```. For classes, what I do is define the ```__call__(self, x)``` function, and then pass the class through as the objective.

For example:
```
import numpy as np
import pybobyqa

class Objfun(object):
    def __call__(self, x):
        return np.sum(x**2)

x0 = np.ones((10,))
f = Objfun()
soln = pybobyqa.solve(f, x0)
```

In your case, I would suggest doing something like
```
class Myclass:
    def obj(self, x):
        return np.sum(x**2)

    def __call__(self, x):  # new code
        return self.obj(x)
```

See here for details: https://docs.python.org/3/reference/datamodel.html#emulating-callable-objects

**Comment by tazuddin90** [comment]
Thank you so much Roberts.. 
Its an excellent job done by you.
You don't know how your model helped me to make my life easy.
Thank you so much for making such a complete package.

**Comment by lindonroberts** [comment]
Thanks, I'm glad it's useful for you!
